repos:
- framework: flask
  language: python
  lastCloned: 2020-05-12 13:34:03.328092
  lastCommitHash: 1e4d3b506cbd6b01bcba13b442cbb0f36f2f4157
  url: https://github.com/mrcodekiddie/summa
- framework: null
  language: html
  lastCloned: 2020-05-12 13:46:38.425992
  lastCommitHash: 
  port: 8500
  url: https://github.com/praba2210/lbmect-web
